// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYxiv2EDEp9AufIk8DNML8VgVwiPu-Gc',
    appId: '1:140172371603:web:3e0f48bfc16ed88096cf66',
    messagingSenderId: '140172371603',
    projectId: 'progra-7f46a',
    authDomain: 'progra-7f46a.firebaseapp.com',
    storageBucket: 'progra-7f46a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1A64u6ReXOYBqzc6ssa_PP2cSZUUCvXs',
    appId: '1:140172371603:android:c1b75a13f905378b96cf66',
    messagingSenderId: '140172371603',
    projectId: 'progra-7f46a',
    storageBucket: 'progra-7f46a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-36pIVFWCUndCc7b_mhu7zjvZM2X8DQ',
    appId: '1:140172371603:ios:fcd085a1495aedd296cf66',
    messagingSenderId: '140172371603',
    projectId: 'progra-7f46a',
    storageBucket: 'progra-7f46a.appspot.com',
    iosBundleId: 'com.example.notistodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc-36pIVFWCUndCc7b_mhu7zjvZM2X8DQ',
    appId: '1:140172371603:ios:9980392dc7a8458396cf66',
    messagingSenderId: '140172371603',
    projectId: 'progra-7f46a',
    storageBucket: 'progra-7f46a.appspot.com',
    iosBundleId: 'com.example.notistodolist.RunnerTests',
  );
}
